//Push {To add} {Adds at end of array}
var ourArray = ['Hello','how','are'];
console.log(ourArray);
ourArray.push('you');
console.log(ourArray);
ourArray.push(['ok']);
console.log(ourArray);

//Pop {To Remove} {Removes last element}

var ourArray1 = ['Hello','fellas'];
console.log(ourArray1);
ourArray1.pop(); //Removes last element
console.log(ourArray1);

//Shift {Removes First element}

var ourArray2 = ['Welcome','Guys'];
console.log(ourArray2);
ourArray2.shift();
console.log(ourArray2);

//unshift {Adds at Beginning of Array}

 var ourArray3 = ['Yo','Sup'];
 console.log(ourArray3);
 ourArray3.unshift('Hey');
 console.log(ourArray3);

 